
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Calendar = lazy(() => import("./pages/Calendar.tsx"));
const Emails = lazy(() => import("./pages/Emails.tsx"));
const GmailAuth = lazy(() => import("./pages/GmailAuth.tsx"));
const GmailCallback = lazy(() => import("./pages/GmailCallback.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/calendar", element: <Calendar />},
	{ path: "/emails", element: <Emails />},
	{ path: "/gmail-auth", element: <GmailAuth />},
	{ path: "/gmailauth", element: <GmailAuth />},
	{ path: "/gmail-callback", element: <GmailCallback />},
	{ path: "/gmailcallback", element: <GmailCallback />},

];
